include:
  - project: 'repos/releng/kokkuri'
    file: 'includes/images.yaml'

default:
  tags:
    - kubernetes

stages:
  - lint
  - test
  - publish

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED

lint-code:
  stage: lint
  extends: .kokkuri:build-and-run-image
  variables:
    BUILD_VARIANT: make
    RUN_ARGUMENTS: '["lint"]'

run-unit-tests:
  stage: test
  extends: .kokkuri:build-and-run-image
  variables:
    BUILD_VARIANT: make
    RUN_ARGUMENTS: '["test"]'

build-frontend:
  stage: test
  extends: .kokkuri:build-image
  variables:
    BUILD_VARIANT: buildkit
    BUILD_TARGET_PLATFORMS: linux/amd64,linux/arm64

# Publish a new version of the buildkit frontend each time a version tag (e.g.
# v0.0.0) is pushed. Note that these tags are marked as protected under 
# https://gitlab.wikimedia.org/repos/releng/blubber/-/settings/repository and
# can only be pushed by project maintainers.
build-and-publish-frontend:
  stage: publish
  extends: .kokkuri:build-and-publish-image
  variables:
    BUILD_VARIANT: buildkit
    BUILD_TARGET_PLATFORMS: linux/amd64 # omit linux/arm64 until T322453 is sorted
    IMAGE_NAME: '${CI_PROJECT_PATH}/buildkit'
  tags:
    - protected
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED
