pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: candidate
        build: production

  rehearse:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: candidate
        build: production
        publish:
          image: true
      - name: rehearsal
        deploy:
          chart:
            name: 'blubberoid'
          image: '${candidate.imageName}'
          tag: '${candidate.imageTag}'
          test: true

  publish:
    blubberfile: blubber.yaml
    stages:
      - name: test
      - name: candidate
        build: production
        publish:
          image: true
      - name: rehearsal
        deploy:
          chart:
            name: 'blubberoid'
          image: '${candidate.imageName}'
          tag: '${candidate.imageTag}'
          test: true
      - name: production
        publish:
          image:
            id: '${candidate.imageID}'
            tags: [stable]
        promote:
          - chart: blubberoid
      - name: print-versions
        build: print-versions
        run:
          tail: 10
      - name: publish-buildkit-gateway
        build: buildkit
        publish:
          image:
            name: blubber-buildkit
            tag: ''
            tags: { $each: version, $in: '${print-versions.output}' }

  # publish the buildkit gateway upon newly pushed git tags
  publish-buildkit-gateway:
    blubberfile: blubber.yaml
    stages:
      - name: publish-buildkit-gateway
        build: buildkit
        publish:
          image:
            name: blubber-buildkit
            tag: '${setup.tag}'
