style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.wikimedia.org/repos/releng/blubber
options:
  tag_filter_pattern: '^v'
  commits:
    #filters:
    #  Type:
    #    - buildkit
  commit_groups:
    title_maps:
      apt: APT
      buildkit: BuildKit
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
