style: gitlab
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://gitlab.wikimedia.org/repos/releng/blubber
options:
  tag_filter_pattern: '^v'
  commit_groups:
    title_maps:
      apt: APT
      buildkit: BuildKit
      php: PHP
      PythonConfig: Python
  header:
    pattern: "^(?:(\\w+)(?:\\.\\w+)?)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
